{
 "title": "Host_Name",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "CHASSIS 28 PORTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/2 : copper(PE01-LVR-BKP): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "4",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/4 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "6",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/6 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "8",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/8 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/10 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "12",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/12 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "14",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/14 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "16",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/16 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "18",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/18 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "20",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/20 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "22",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/22 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "24",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/24 : copper(FW-GERENCIA): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 1 },
   "content": "\n",
   "targets": [
    {
     "application": { "filter": "Serviços" },
     "group": { "filter": "Backbone Switch" },
     "host": {
      "filter": "SW-PROVEDOR DATACOM (Edificil eldorado )"
     },
     "item": { "filter": "Status Spanning Tree" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/1 : copper(SW-PSO-2): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "3",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/3 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "5",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/5 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "7",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 7, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/7 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/9 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "11",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/11 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "13",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/13 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/15 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "17",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/17 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "19",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/19 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "21",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/21 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "23",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Gi1/0/23 : copper(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "25",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/25 : fiber(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "26",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/26 : fiber(): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "27",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/27 : fiber(PE01-LVR-PSO): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "28",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 1, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/28 : fiber(S2.PSO): Status Operacional"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "SYSTEM INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HOST",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Nome do Dispositivo" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "FIRMWARE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Inventory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Firmware version" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 6 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ICMP PING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "ICMP Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Disponibilidade do SNMP" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LATENCIA",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "ICMP Latencia" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MODELO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Inventory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Hardware model name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MODELO",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Descrição do Equipamento" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SERIAL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Inventory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "Hardware serial number" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU UTILIZADA",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "#1: CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MEMORIA UTILIZADA",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": { "filter": "#1: Memory utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "UPLINK AGREGADO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/28 : fiber (S2.PSO): Download"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Rede" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Host_Name" },
     "item": {
      "filter": "Interface Te1/0/28 : fiber (S2.PSO): Upload"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}